In [1]:
import numpy as np

In [2]:
an_array = np.array([3,33,333]) 
print(type(an_array))

<class 'numpy.ndarray'>


In [3]:
print(an_array.shape)

(3,)


In [4]:
print(an_array[0], an_array[1], an_array[2])

3 33 333


In [5]:
an_array[0]=888
print(an_array)

[888  33 333]


In [11]:
an_array[2]=444
print(an_array)

[888  33 444]


In [13]:
another = np.array([[11,12,13], [21,22,23]])
print(another)
print("The shape is 2 rows, 3 columnss:", another.shape)
print("Accessing elements [0,0], [0,1], and [1,0] of the ndarray:", another[0,0], ",", another[1,0])

[[11 12 13]
 [21 22 23]]
The shape is 2 rows, 3 columnss: (2, 3)
Accessing elements [0,0], [0,1], and [1,0] of the ndarray: 11 , 21


In [14]:
ex1 = np.zeros((2,2))
print(ex1)

[[0. 0.]
 [0. 0.]]


In [16]:
ex2 = np.full((2,2), 9.0)
print(ex2)

[[9. 9.]
 [9. 9.]]


In [17]:
ex3 = np.eye(2,2)
print(ex3)

[[1. 0.]
 [0. 1.]]


In [18]:
ex4 = np.ones((1,2))
print(ex4)

[[1. 1.]]


In [19]:
print(ex4.shape)
print()
print(ex4[0,1])

(1, 2)

1.0


In [23]:
ex5 = np.random.random((2,2))
print(ex5)

[[0.97411145 0.86667167]
 [0.01519857 0.02520199]]


In [28]:
ex6 = np.random.randint((2,2))
print(ex6)

[0 1]


In [29]:
an_array = np.array([[11,12,13,14], [21,22,23,24],[31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [30]:
a_slice = an_array[:2, 1:3]
print(a_slice)

[[12 13]
 [22 23]]


In [31]:
print("Before:", an_array[0,1])
a_slice[0,0] = 1000
print("After:", an_array[0,1])

Before: 12
After: 1000


In [32]:
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [35]:
row_rank1 = an_array[1, :]
print(row_rank1, row_rank1.shape)

[21 22 23 24] (4,)


In [36]:
row_rank2 = an_array[1:2, :]
print(row_rank2, row_rank2.shape)

[[21 22 23 24]] (1, 4)


In [38]:
print()
col_rank1 = an_array [:, 1]
col_rank2 = an_array [:, 1:2]
print(col_rank1, col_rank1.shape)
print()
print(col_rank2, col_rank2.shape)


[12 22 32] (3,)

[[12]
 [22]
 [32]] (3, 1)


In [41]:
an_array =np.array([[11,12,13], [21,22,23], [31,32,33], [41,42,43]])
print('Original Array:')
print(an_array)

Original Array:
[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


In [42]:
col_indices =np.array([0,1,2,0])
print('\nCol indices picked:', col_indices)
row_indices = np.arange(4)
print('\nRows indices picked:', row_indices)


Col indices picked: [0 1 2 0]

Rows indices picked: [0 1 2 3]


In [43]:
for row,col in zip (row_indices,col_indices):
    print(row,",",col)

0 , 0
1 , 1
2 , 2
3 , 0


In [44]:
print('Values in the array at those indices:',an_array[row_indices,col_indices])


Values in the array at those indices: [11 22 33 41]


In [45]:
an_array[row_indices, col_indices] += 100000
print('\nChanged Array:')
print(an_array)


Changed Array:
[[100011     12     13]
 [    21 100022     23]
 [    31     32 100033]
 [100041     42     43]]


In [3]:
import numpy as np

In [4]:
an_array = np.array([[11,12],[21,22],[31,32]])
print(an_array)

[[11 12]
 [21 22]
 [31 32]]


In [5]:
filter = (an_array>15)
filter

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [6]:
print(an_array[filter])

[21 22 31 32]


In [7]:
an_array[an_array >15]

array([21, 22, 31, 32])

In [8]:
an_array[an_array % 2 ==0] +=100
print(an_array)

[[ 11 112]
 [ 21 122]
 [ 31 132]]


datatypes

In [9]:
ex1 = np.array([11,12])
print(ex1.dtype)

int32


In [10]:
ex2 = np.array([11.1,12.7], dtype=np.int64)
print(ex2.dtype)

int64


In [11]:
ex3= np.array([11.0, 12.0])
print(ex3.dtype)

float64


In [13]:
ex4 = np.array([11.1,12.7], dtype=np.int64)
print(ex4.dtype)
print()
print(ex4)

int64

[11 12]


In [14]:
ex5 = np.array([11,12], dtype=np.float64)
print(ex5.dtype)
print()
print(ex5)

float64

[11. 12.]


In [16]:
x = np.array([[111,112],[121,122]], dtype=np.int)
y = np.array([[211.1,212.1],[221.1,222.]], dtype=np.float64)
print(x)
print()
print(y)

[[111 112]
 [121 122]]

[[211.1 212.1]
 [221.1 222. ]]


add

In [17]:
print(x+y)
print()
print(np.add(x,y))

[[322.1 324.1]
 [342.1 344. ]]

[[322.1 324.1]
 [342.1 344. ]]


subtract

In [18]:
print(x-y)
print()
print(np.subtract(x,y))

[[-100.1 -100.1]
 [-100.1 -100. ]]

[[-100.1 -100.1]
 [-100.1 -100. ]]


In [19]:
print(x * y)
print()
print(np.multiply(x,y))

[[23432.1 23755.2]
 [26753.1 27084. ]]

[[23432.1 23755.2]
 [26753.1 27084. ]]


In [21]:
#divide
print(x / y) 
print()
print(np.multiply(x,y))

[[0.52581715 0.52805281]
 [0.54726368 0.54954955]]

[[23432.1 23755.2]
 [26753.1 27084. ]]


In [22]:
print(x ** y)
print()
print(np.multiply(x,y))

[[inf inf]
 [inf inf]]

[[23432.1 23755.2]
 [26753.1 27084. ]]


<ipython-input-22-84236e957573>:1: RuntimeWarning: overflow encountered in power
  print(x ** y)


squareroot

In [24]:
print(np.sqrt(x))

[[10.53565375 10.58300524]
 [11.         11.04536102]]


exponent (e**x)

In [27]:
print(np.exp(x))

[[1.60948707e+48 4.37503945e+48]
 [3.54513118e+52 9.63666567e+52]]


basic statistiacal operations

In [29]:
arr = 10 * np.random.randn(2,5)
print(arr)

[[  0.93052572  -8.74917065  -6.01719607   9.50196938  -0.76866953]
 [  9.64516409  -2.22323613  -3.1885788    6.12461629 -10.19003726]]


In [30]:
print(arr.mean())

-0.4934612955017088


compute mean by row

In [32]:
print(arr.mean(axis = 1))

[-1.02050823  0.03358564]


compute the mean by column

In [33]:
print(arr.mean(axis = 0))

[ 5.2878449  -5.48620339 -4.60288744  7.81329284 -5.47935339]


sum all the element

In [34]:
print(arr.sum())

-4.934612955017088


compute the median

In [35]:
print(np.median(arr, axis = 1))

[-0.76866953 -2.22323613]


In [36]:
print(np.median(arr, axis = 0))

[ 5.2878449  -5.48620339 -4.60288744  7.81329284 -5.47935339]


sorting

creat 10 element array of random

In [37]:
unsorted = np . random.randn(10)
print(unsorted)

[ 0.43414316  0.11648748 -1.70574522 -0.893082    0.69312306  3.24485554
  0.85648182  2.02042329 -1.03208853  0.70628695]


In [38]:
unsorted = np . random.randn(10,2)
print(unsorted)

[[ 1.18082212  1.46108342]
 [ 0.11882185 -0.48966666]
 [ 3.08364014 -0.42977789]
 [ 1.74937318  0.74484315]
 [-2.02258932 -0.0816638 ]
 [-0.52194973 -0.29707482]
 [ 1.49404412 -1.21201712]
 [ 0.85637453 -1.03091108]
 [ 0.20301101 -0.52879539]
 [-0.57499222  0.83689565]]


creat copy and sort

In [39]:
sorted = np.array(unsorted)
sorted.sort()
print(sorted)
print()
print(unsorted)

[[ 1.18082212  1.46108342]
 [-0.48966666  0.11882185]
 [-0.42977789  3.08364014]
 [ 0.74484315  1.74937318]
 [-2.02258932 -0.0816638 ]
 [-0.52194973 -0.29707482]
 [-1.21201712  1.49404412]
 [-1.03091108  0.85637453]
 [-0.52879539  0.20301101]
 [-0.57499222  0.83689565]]

[[ 1.18082212  1.46108342]
 [ 0.11882185 -0.48966666]
 [ 3.08364014 -0.42977789]
 [ 1.74937318  0.74484315]
 [-2.02258932 -0.0816638 ]
 [-0.52194973 -0.29707482]
 [ 1.49404412 -1.21201712]
 [ 0.85637453 -1.03091108]
 [ 0.20301101 -0.52879539]
 [-0.57499222  0.83689565]]


In [40]:
unsorted = np . random.randn(10)
print(unsorted)

[ 0.39667514 -1.05695254 -0.36193015 -0.5407064   2.00072749 -0.91634345
  0.00971058 -0.92115643 -0.6301377  -1.62778157]


In [41]:
sorted = np.array(unsorted)
sorted.sort()
print(sorted)
print()
print(unsorted)

[-1.62778157 -1.05695254 -0.92115643 -0.91634345 -0.6301377  -0.5407064
 -0.36193015  0.00971058  0.39667514  2.00072749]

[ 0.39667514 -1.05695254 -0.36193015 -0.5407064   2.00072749 -0.91634345
  0.00971058 -0.92115643 -0.6301377  -1.62778157]


In [42]:
#inplace sorting
print(unsorted)

[ 0.39667514 -1.05695254 -0.36193015 -0.5407064   2.00072749 -0.91634345
  0.00971058 -0.92115643 -0.6301377  -1.62778157]


finding unique element

In [43]:
array = np.array([1,2,1,4,2,1,4,2])
print(np.unique(array))

[1 2 4]


set operation with np.array datatype:

In [44]:
s1 = np.array(['desk', 'chair', 'bulb'])
s2 = np.array(['lamp', 'bulb', 'chair'])
print(s1,s2)

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']


In [46]:
print(np.intersect1d(s1,s2))

['bulb' 'chair']


In [48]:
print(np.union1d(s1,s2))

['bulb' 'chair' 'desk' 'lamp']


In [49]:
#element in s1 that are not in s2
print(np.setdiff1d(s1,s2))


['desk']


In [50]:
#which element of s1 is also in s2
print(np.in1d(s1,s2))

[False  True  True]


brodcasting:

In [51]:
import numpy as np
start = np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [52]:
#creat a rank 1 nd array with 3 values
add_rows = np.array([1,0,2])
print(add_rows)

[1 0 2]


In [53]:
#add to each row of 'start' using broadcasting
y = start + add_rows
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [54]:
#creat an ndarray which is 4*1 to broadcasting across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [55]:
#add to each column of 'start' using broadcasting
y = start + add_cols
print(y)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [56]:
#this will just broadcast in both dimensions
add_scalar = np.array([1])
print(start+add_scalar)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [57]:
#creat our 3*4 matrix
arrA = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arrA)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [58]:
#creat our 4*1 matrix
arrB = [0,1,0,2]
print(arrB)

[0, 1, 0, 2]


In [59]:
#add the two together using broadcasting
print(arrA + arrB)

[[ 1  3  3  6]
 [ 5  7  7 10]
 [ 9 11 11 14]]


first step parameters for the speed test. we'll be testing time to sum elemnts in an ndarray versus a list

In [60]:
from numpy import arange
from timeit import Timer
size = 1000000
timeits = 1000

In [61]:
#creat the ndarray woth values 0,1,2,....,size-1
nd_array = arange(size)
print(type(nd_array))

<class 'numpy.ndarray'>


In [64]:
#time expects the operation as parameter
#here we pass nd_array.sum()
timer_numpy = Timer("nd_array.sum()", "from __main__ import nd_array")
print("Time taken by numpy ndarray: %f seconds" %
     (timer_numpy.timeit(timeits)/ timeits))

Time taken by numpy ndarray: 0.000849 seconds


In [65]:
#creat the list with values 0,1,2,....., size-1
a_list = list(range(size))
print(type(a_list))

<class 'list'>


In [67]:
#timer expects the operation as a parameter, here we pass sum(a_list)
timer_list = Timer("sum(a_list)", "from __main__ import a_list")
print("Time taken by list: % f seconds" %
     (timer_list.timeit(timeits)/timeits))

Time taken by list: 0.043808 seconds


In [1]:
import numpy as np

In [2]:
an_array = np.array([3,33,333]) 
print(type(an_array))

<class 'numpy.ndarray'>


binary formate

In [3]:
x = np.array([23.23, 24.24])

In [4]:
np.save('an_array', x)

In [6]:
np.load('an_array.npy')

array([23.23, 24.24])

text formate

In [8]:
np.savetxt('array.txt', X=x, delimiter=',')

In [10]:
np.loadtxt('array.txt', delimiter=',')

array([23.23, 24.24])

dot product on matrices and inner product on vectors

In [11]:
#determine the dot product of two matrix
x2d = np.array([[1,1], [1,1]])
y2d = np.array([[2,2], [2,2]])
print(x2d.dot(y2d))
print()
print(np.dot(x2d,y2d))

[[4 4]
 [4 4]]

[[4 4]
 [4 4]]


In [12]:
#detremine the inner product of two vectors
a1d =np.array([9 , 9])
b1d =np.array([10,10])
print(a1d.dot(b1d))
print()
print(np.dot(a1d,b1d))


180

180


In [13]:
#dot produce on an array and vectore
print(x2d.dot(a1d))
print()
print((np.dot(x2d, a1d)))

[18 18]

[18 18]


In [14]:
#sum element in the array
ex1 = np.array([[11,12], [21,22]])
print(np.sum(ex1))      #add all members

66


In [15]:
print(np.sum(ex1, axis=0))   #columnwise sum

[32 34]


In [16]:
print(np.sum(ex1, axis=1))   #rowwise

[23 43]


element wise functions
for ex let's compare two array values to get the maximum of each

In [17]:
#random array
x = np.random.randn(8)
x

array([-1.82550003,  1.02087992,  0.20188147, -0.16038529,  2.37227984,
        1.12665671, -0.97971506,  1.3573337 ])

In [18]:
#another random array
y = np.random.randn(8)
y

array([-1.67369211,  0.41613447,  0.02283347, -1.14755789,  0.2080276 ,
        0.59542647,  0.2028666 , -0.14535798])

In [23]:
#return element wise maximum btn two array
import numpy as np
x = np.random.randn(8)
y = np.random.randn(8)
np.maximum(x, y)

array([-0.30709246,  1.21568214,  0.52442473, -0.19399004, -0.34029777,
        0.16002586,  0.41828567,  1.19068083])

In [24]:
#reshaping array
#grab values from 0 through 19 in an array
arr = np.arange(20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [25]:
#reshape to be a 4*5 matrix
arr.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [26]:
#teanspose
ex1 = np.array([[11,12], [21,22]])
ex1.T

array([[11, 21],
       [12, 22]])

In [27]:
#indexing using where()
x_1 = np.array([1,2,3,4,5])
y_1 = np.array([11,22,33,44,55])
filter = np.array([True, False, True, False, True])

In [28]:
out = np.where(filter, x_1, y_1)
print(out)

[ 1 22  3 44  5]


In [29]:
mat = np.random.randn(5,5)
mat

array([[-1.63689266,  1.10505959, -1.28142418,  1.06472119, -1.95349557],
       [ 0.30117688, -0.23250216, -0.11453486, -2.21459276,  0.00590238],
       [-1.11168943, -0.09577786,  0.46453272, -1.061579  , -1.47559267],
       [-1.48881381, -0.45039798, -0.15620951, -1.72096204,  2.07902618],
       [-0.01690114, -0.49481136, -0.83092827,  0.34267505,  0.52748394]])

In [32]:
np.where(mat> 0.5, 1000, -1)  #"""if mat>0.5:
      #replace(1000)
   # else:
      #replace(-1)"""



array([[  -1, 1000,   -1, 1000,   -1],
       [  -1,   -1,   -1,   -1,   -1],
       [  -1,   -1,   -1,   -1,   -1],
       [  -1,   -1,   -1,   -1, 1000],
       [  -1,   -1,   -1,   -1, 1000]])

In [33]:
#"any" or "all" conditionals
arr_bools =np.array([True, False,True, True,False])

In [34]:
arr_bools.any()

True

In [35]:
arr_bools.all()

False

In [36]:
#random no generation

import numpy as np
Y = np.random.normal(size = (1,5))[0]
print(Y)

[ 0.05867462  0.41535458 -0.41906411  0.06842998 -0.28447667]


In [37]:
Z = np.random.randint(low=2, high=50, size=4)
print(Z)

[ 3 35 28 18]


In [39]:
np.random.permutation(Z)     #return a new ordering of element in Z

array([ 3, 18, 35, 28])

In [40]:
np.random.uniform(size=4)    #uniform distribution 

array([0.43391592, 0.3109726 , 0.3348869 , 0.36761402])

In [42]:
np.random.normal(size=4)    #normal distribution

array([ 0.51184578, -0.55799044, -0.49328688, -0.25776266])

In [44]:
K = np.random.randint(low=2,high=50,size=(2,2))
print(K)

print()
M = np.random.randint(low=2,high=50,size=(2,2))
print(M)

[[18 28]
 [21 43]]

[[34 14]
 [48 20]]


In [45]:
np.vstack((K,M))

array([[18, 28],
       [21, 43],
       [34, 14],
       [48, 20]])

In [47]:
np.hstack((K,M))

array([[18, 28, 34, 14],
       [21, 43, 48, 20]])

In [48]:
np.concatenate([K,M],axis = 0)

array([[18, 28],
       [21, 43],
       [34, 14],
       [48, 20]])

In [49]:
np.concatenate([K,M.T],axis =1)

array([[18, 28, 34, 48],
       [21, 43, 14, 20]])